import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ChangeTheme from "@/components/ChangeTheme";
import { Work_Sans } from "next/font/google";



const work_Sans = Work_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${work_Sans.className} antialiased`}
      >
        <Header />
        {/* <ChangeTheme /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
